#!/bin/bash
# Update the system packages
dnf update -y
# Install Apache HTTP Server (httpd)
dnf install -y httpd
# Start the Apache service
systemctl start httpd
# Enable Apache to start on system boot
systemctl enable httpd
# Create an index.html file with a custom response
echo "<html> <h1> Response coming from server </h1> </html>" > /var/www/html/index.html
# Restart the Apache service for changes to take effect
systemctl restart httpd
